### ISSUE TITLE
Confirmation page

### ISSUE THREAD

**Issue by roddas** [Ko-Vatuvembela/front_end#20]
## Description
After create an account, the user must login and confirms his account.

## Tasks
- [ ] Create the page which the user inserts the confirmation code
- [x] The application must have a middleware to check if the user is confirmed

## Evaluation criteria
- [ ]  The page must be integrated to the backend server
