### ISSUE TITLE
Acabamentos

### ISSUE THREAD

**Issue by roddas** [Ko-Vatuvembela/front_end#28]
## Description
Implementar funcionalidades pouco importantes

## Tasks
- [ ] Eliminar um provérbio, se for o criador
- [ ] Criar paginação de conteúdos
- [ ] Editar um provérbio, se for o criador
- [ ] Eliminar uma postagem na gramática, se for o criador
- [ ] Editar uma postagem na gramática, se for o criador
- [ ] Guardar os provérbios e as línguas em cache, para evitar acessos ao banco

## Evaluation criteria
- [ ]  As funcionalidades acima descritas devem ser implementadas.
