### ISSUE TITLE
Optimização

### ISSUE THREAD

**Issue by roddas** [Ko-Vatuvembela/front_end#31]
## Description
A aplicação deve ter sistema de cache

## Tasks
- [x] Criar context de línguas
- [x] Criar context de provérbios
- [x] Guardar em cache as informações
