### ISSUE TITLE
Login and session handling

### ISSUE THREAD

**Issue by roddas** [Ko-Vatuvembela/front_end#8]
## Description
The user must perform the login and logout and handles his session.

## Tasks
- [x] Setup the session handling
- [x] Integrate the backend server to front end server

## Evaluation criteria
- [x]  Both backend and frontend servers must be integrated
- [x] The user must be able to login and logout whenever he  wants.
